In [167]:
import numpy as np
import pandas as pd

In [168]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline,make_pipeline

In [169]:
df=pd.read_csv('titanic_data.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [170]:
df=df.drop(columns=['PassengerId','Name', 'Cabin','Ticket'])

In [171]:
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']), df['Survived'],test_size=0.2, random_state=42)

In [172]:
x_train.head()

     Pclass   Sex   Age  SibSp  Parch     Fare Embarked
336       2  male  32.0      0      0  13.0000        S
31        2  male  24.0      2      0  31.5000        S
84        2  male   NaN      0      0  10.7083        Q
287       1  male  24.0      1      0  82.2667        S
317       2  male  19.0      0      0  10.5000        S

# 1 Column Transfermer for the missing values in the age and embarked

In [173]:
trf1=ColumnTransformer(transformers=[
    ('imputed_age',SimpleImputer(),[2]),
    ('imputed_embarked',SimpleImputer(strategy='most_frequent'),[6])
], remainder='passthrough')

# 2 onehot encoding of sex and Embarked column

In [174]:
trf2=ColumnTransformer(transformers=[
    ('ohe_sex_embarked',OneHotEncoder(sparse_output=False,handle_unknown='ignore'),[1,6])
    ], remainder='passthrough')

# 3 scaling the feature through minmax scaling

In [175]:
trf3=ColumnTransformer(transformers=[
    ('scale',MinMaxScaler(),slice(0,10))
    ], remainder='passthrough')

# 4 select kbest feature

In [176]:
trf4=SelectKBest(score_func=chi2,k=8)

# 5 DecsionTreeClassifier

In [177]:
trf5=DecisionTreeClassifier()

# 6 Now making pipelines

In [178]:
pipe=Pipeline([
    ('trf1', trf1),
    ('trf2', trf2),
    ('trf3', trf3),
    ('trf4', trf4),
    ('trf5', trf5)
])

# 7 Fit the data

In [179]:
pipe.fit(x_train,y_train)

ValueError: could not convert string to float: 'male'